get_filename_component(_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set (log4cxx_INCLUDE_DIRS "${_PREFIX}/include")
set (log4cxx_LIBRARIES debug "${_PREFIX}/lib/log4cxxd.lib" optimized "${_PREFIX}/lib/log4cxx.lib")

set (log4cxx_INCLUDE_DIR "${log4cxx_INCLUDE_DIRS}")
set (LOG4CXX_INCLUDE_DIRS "${log4cxx_INCLUDE_DIRS}")
set (LOG4CXX_INCLUDE_DIR "${log4cxx_INCLUDE_DIRS}")
set (log4cxx_LIBRARY "${log4cxx_LIBRARIES}")
set (LOG4CXX_LIBRARIES "${log4cxx_LIBRARIES}")
set (LOG4CXX_LIBRARY "${log4cxx_LIBRARIES}")
